homepage:
    path: /
    controller: App\Controller\CryptoController::afficher

index :
    path: index
    controller: App\Controller\CryptoController::index

login :
    path: login
    controller: App\Controller\CryptoController::login

#logout :
#    path: logout
#    controller: App\Controller\CryptoController::logout

register :
    path: register
    controller : App\Controller\RegistrationController::register

admin :
    path: /admin
    controller : App\Controller\AdminController::admin

crypto_show:
   path: /show/{id}
   controller: App\Controller\CryptoController::show

ajouter_droit:
   path : /ajouter_droit
   controller : App\Controller\AdminController::ajouter_droit

supprimer_uti:
   path : /supprimer_uti/{id}
   controller : App\Controller\AdminController::supprimer_uti

#commentaire_add:
#    path:
#    controller:

#crypto_fav:
#    path:
#    controller:

crypto_add:
    path: /add
    controller : App\Controller\CryptoController::add

crypto_delete:
    path: /delete/{id}
    controller: App\Controller\CryptoController::delete
    requirements:
        id: '\d+'

crypto_edit:
    path: /edit/{id}
    controller: App\Controller\CryptoController::edit
    requirements:
        id: '\d+'